version: '3.1'

services:
    db:
        image: postgres:9.6
        restart: always  
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres-gdrt-data-volume:/var/lib/postgresql/data
    rest:
        image: postgrest/postgrest
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - db
        volumes:
            - ./postgrest_config.cfg:/etc/postgrest.conf
    web:
        image: openresty/openresty
        restart: always
        depends_on:
            - rest
        ports:
            - "80:80"
        volumes:
            - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf
            - ./build:/usr/local/openresty/nginx/html
volumes:
    postgres-gdrt-data-volume:
        external: true
