export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const REQUEST_GRIDS = 'REQUEST_GRIDS';
export const RECEIVE_GRIDS = 'RECEIVCE_GRIDS';

export const RECEIVE_CASCADE_SELECT = 'RECEIVE_CASCADE_SELECT';
export const REQUEST_CASCADE_SELECT = 'REQUEST_CASCADE_SELECT';

export const REQUEST_METHODS = 'REQUEST_METHODS';
export const RECEIVE_METHODS = 'RECEIVE_METHODS'; 